### ISSUE TITLE
Events fired from transaction callback are not received

### ISSUE THREAD

**Issue by mitchjust-finocomp** [grails/grails-async#36]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Attempt to fire an event from within the `afterCommit` callback of a `TransactionSynchronizationAdapter`

### Expected Behaviour

The event should be received by listeners

### Actual Behaviour

The event is not received by listeners

### Environment Information

- **Operating System**: Ubuntu 20.04
- **Grails Version:** 4.0.3
- **JDK Version:** (Zulu 8.46.0.19-CA-linux64) (build 1.8.0_252-b14)

### Example Application

- https://github.com/mitchjust-finocomp/grails-4-event-bug

### Notes

This is existing code in a grails 3.2 app migrated to 4.0.3, so firing events like this used to work.

It seems to be associated with the thread which the event is fired from, as wrapping the publish in a promise seems to make it work.

**Comment by puneetbehl** [comment]
It is not working because you are not providing any implementation for `notificationTrigger`. See [AbstractEventBus.groovy#L128](https://github.com/grails/grails-async/blob/v4.0.0/grails-events/src/main/groovy/org/grails/events/bus/AbstractEventBus.groovy#L128). The `afterCommit` is correctly triggered but does nothing apart from adding a synchronization.

In the above sample application, it is adding synchronization later in the stage when `notify("myEventTag${num}", Instant.now())` is called from the transaction after commit is trigger and `notificationTrigger.run()` is never executed. I think you can directly call the following instead of registering TransactionSynchronizationAdaptor as:
```
@Transactional(propagation = Propagation.REQUIRES_NEW)
void doSomething() {
      String random = RandomStringUtils.random(20, true, false)
      log.info('Saving a new SomeDomain: '+ random)
      new SomeDomain(text: random).save()
      notify(Event.from("myEventTag1", Instant.now()), TransactionPhase.AFTER_COMMIT)
}
``` 



It works when you call `notify` in a `Promise` because `TransactionSynchronizationManager.synchronizations.get` is null in the new thread and the other branch of `notify(Event)` method is called [here](https://github.com/grails/grails-async/blob/v4.0.0/grails-events/src/main/groovy/org/grails/events/bus/AbstractEventBus.groovy#L90)

**Comment by mitchjust-finocomp** [comment]
thanks @puneetbehl
